### ISSUE TITLE
Programmatically stop application

### ISSUE THREAD

**Issue by Swoogan** [non-standard/atlas#5]
Once my service is running, how do I stop it programmatically?

My `Start()` method kicks off a thread that runs a loop. The loop checks a ManualResetEvent and exits if it's set. I have a situation where the app needs to close and sets the ManualResetEvent which breaks the loop, but the app just hangs at this point.

Is there some way to tell Atlas that I want to quit?

**Comment by vizyviz** [comment]
Hi, depending on what mode your app is running in, you should just either stop the service, or hit the esc key to stop the service from running.  Are you running as a Windows Service or a Console Application?

If you are willing to share your code with me I'd be happy to help more, but without seeing your run loop or how you are using the manual reset event I don't know how else to help.

**Comment by Swoogan** [comment]
I'm running in the console, but there is no user to hit ESC or stop the service. The app needs to close itself.

```
public void Start()
{
	Task.Run((Action) Execute);
}

private void Execute()
{
	while (true)
	{
		Update();
		
		if (_shutdownEvent.WaitOne(0))
		{
			Logger.Info("Shutting down");
			break;
		}

		DoWork();
	}

	Logger.Debug("Loop broke");
}

private void Update()
{
	var version = GetLatestVersion();
	
	if (IsVersionNewer(version))
	{
		Logger.Info("Upgrading to version {0}", version);
		UpdateToVersion(version);
		_shutdownEvent.Set();
	}
}
```

When an update is available `_shutdownEvent` is set and the loop exits. The line "Loop broke" will be written to the console, but then the app hangs. Atlas can tell my app to quit, but I don't see how to tell Atlas my app wants to quit.

**Comment by vizyviz** [comment]
Ah, I think I understand now.  You want the service/app to stop on some signal from within your app? There isn't a means in Atlas to currently programmatically exit.  However, you can use Environment.Exit(0); to tell the process to exit with an exit code of 0.  Just make sure you do your clean up before you call it.  I can add in a means to programmatically stop a service into the API, but it may take me some time to get to it.  I'm always happy to take pull requests.  I can merge them in and release a new build on nuget pretty quickly.
